import React from "react";
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer } from "recharts";

const COLORS = ["#4fbeff", "#f9c66d", "#6de3a9", "#f38b8b", "#b794f6"];

export default function Home({ report }) {
  const holdings = report?.holdings || {};
  const data = Object.values(holdings).map((item) => ({
    name: item.symbol,
    value: Number(item.value_usd || 0),
  }));

  return (
    <div className="page">
      <section className="hero">
        <div>
          <div className="pill">Automated PnL Intelligence</div>
          <h1>Portfolio Tracker PnL</h1>
          <p>
            Live-ready reporting for multi-wallet crypto portfolios. Track balances, value, and
            daily change with automated scheduling and a polished dashboard.
          </p>
          <div className="tag">
            <span className="pill">Base: {report.base_currency}</span>
            <span className="pill">Report: {report.date}</span>
          </div>
        </div>
        <div className="panel">
          <h2>Total Portfolio Value</h2>
          <div className="stat-value">${report.total_value_usd.toLocaleString()}</div>
          <p className="muted">
            Daily change {report.daily_change_percent >= 0 ? "+" : ""}
            {report.daily_change_percent}% ({report.change_usd >= 0 ? "+" : ""}
            {report.change_usd.toLocaleString()})
          </p>
          <p className="muted">Last updated {new Date(report.timestamp).toLocaleString()}</p>
        </div>
      </section>

      <section className="stats">
        <div className="stat-card">
          <div className="stat-label">Wallets Tracked</div>
          <div className="stat-value">{report.wallets?.length || 0}</div>
        </div>
        <div className="stat-card">
          <div className="stat-label">Assets Covered</div>
          <div className="stat-value">{Object.keys(holdings).length}</div>
        </div>
        <div className="stat-card">
          <div className="stat-label">Top Asset</div>
          <div className="stat-value">
            {data.length ? data.sort((a, b) => b.value - a.value)[0].name : "N/A"}
          </div>
        </div>
      </section>

      <section className="layout">
        <div className="card">
          <h2>Allocation</h2>
          <div style={{ width: "100%", height: 280 }}>
            <ResponsiveContainer>
              <PieChart>
                <Pie data={data} dataKey="value" outerRadius={90} label>
                  {data.map((entry, index) => (
                    <Cell key={entry.name} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip formatter={(value) => `$${Number(value).toLocaleString()}`} />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="card">
          <h2>Holdings</h2>
          <div className="holdings">
            {Object.values(holdings).map((item) => (
              <div className="holding-row" key={item.symbol}>
                <div>
                  <div className="tag">
                    <strong>{item.symbol}</strong>
                    <span className="pill">{item.chain}</span>
                  </div>
                  <div className="muted">
                    {item.balance.toFixed(4)} @ ${item.price_usd.toLocaleString()}
                  </div>
                </div>
                <strong>${item.value_usd.toLocaleString()}</strong>
              </div>
            ))}
          </div>
        </div>
      </section>

      <footer className="footer">
        Generated by the automated tracker. Connect a webhook or schedule runs via GitHub Actions.
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const { getLatestReport } = await import("../lib/report");
  const report = getLatestReport();
  return { props: { report } };
}
